"""
Pydantic schemas describing the shape of documents stored in MongoDB.
MongoDB itself enforces no schema, so these models are our contract —
validate data against them before inserting, and parse data through
them after reading.
"""

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field

class ArchitectureComponent(BaseModel):
    """A single detected AI component (e.g. LLM, RAG, Tool Calling)."""
    name: str
    component_type: str        # will become an enum in Phase 1 Step 9
    confidence: float = Field(ge=0.0, le=1.0)
    source_text: Optional[str] = None

class AnalysisRecord(BaseModel):
    """
    Top-level record for one user analysis session —
    one uploaded document/architecture = one AnalysisRecord.
    """
    analysis_id: str
    filename: Optional[str] = None
    raw_text: Optional[str] = None
    components: List[ArchitectureComponent] = []
    created_at: datetime = Field(default_factory=datetime.utcnow)
    status: str = "pending"   # pending | analyzed | failed

class HealthCheckRecord(BaseModel):
    """Tiny record used only to verify DB read/write works (Phase 1 test)."""
    checked_at: datetime = Field(default_factory=datetime.utcnow)
    ok: bool

class TechniqueMapping(BaseModel):
    """One matched ATLAS technique, with the component(s) that triggered it."""
    technique_id: str
    technique_name: str
    tactic_id: Optional[str] = None
    tactic_name: str
    maturity: Optional[str] = None
    url: str
    matched_components: List[str] = []

class AtlasMappingRecord(BaseModel):
    """Result of running Phase 4 mapping against one AnalysisRecord."""
    mapping_id: str
    analysis_id: str
    techniques: List[TechniqueMapping] = []
    tactic_summary: dict = {}   # {"Execution": 3, "Persistence": 2, ...}
    created_at: datetime = Field(default_factory=datetime.utcnow)

class AttackStep(BaseModel):
    """A single step inside an attack path."""
    step: int
    technique_id: str
    technique_name: str
    action: str
    leads_to: str


class AttackPath(BaseModel):
    """A complete multi-step attack chain generated by Gemini."""
    path_id: str
    name: str
    entry_point: str
    steps: List[AttackStep]
    final_impact: str
    likelihood: float = Field(ge=0, le=10)
    impact: float = Field(ge=0, le=10)
    exposure: float = Field(ge=0, le=10)
    risk_score: float = 0.0
    risk_level: str = "Unknown"
    ai_explanation: str = ""
    mitigations: List[dict] = []


class AttackPathRecord(BaseModel):
    """Top-level MongoDB record storing all attack paths for one analysis."""
    analysis_id: str
    filename: Optional[str] = None
    attack_paths: List[AttackPath] = []
    total_paths: int = 0
    highest_risk_score: float = 0.0
    overall_risk_level: str = "Unknown"
    created_at: datetime = Field(default_factory=datetime.utcnow)
    status: str = "pending"   